### ISSUE TITLE
deprecated "role in human social processes" (OMRSE:00000024) vs.  "role in human social processes" (OMRSE:00002072) problem

### ISSUE THREAD

**Issue by StroemPhi** [mcwdsi/OMRSE#188]
Hi, 
while building import modules for my ontology with the latest ODK, I stumbled across the fact that the deprecated class ["role in human social processes" OMRSE:00000024](https://www.ebi.ac.uk/ols/ontologies/omiabis/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMRSE_00000024) is still being reused by many other ontologies instead of the one that, according to https://github.com/ufbmi/OMRSE/issues/177 was probably ment to replace it, but which seems to be just the same with a new ID, namely [ "role in human social processes" OMRSE:00002072](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMRSE_00002072).

**Comment by StroemPhi** [comment]
Looking at #181, I see that the difference lies within change of the subclassOf axiomatization in both classes from:
```
SubClassOf(obo:OMRSE_00000024 obo:BFO_0000023)
SubClassOf(obo:OMRSE_00000024 ObjectAllValuesFrom(obo:RO_0000052 ObjectUnionOf(obo:OBI_0000245 obo:OBI_0100026)))
```
to 
```
SubClassOf(obo:OMRSE_00002072 obo:BFO_0000023)
SubClassOf(obo:OMRSE_00002072 ObjectSomeValuesFrom(obo:RO_0000052 obo:BFO_0000040))
SubClassOf(obo:OMRSE_00002072 ObjectAllValuesFrom(obo:RO_0000052 obo:BFO_0000040))
```
If I understand it right, the change from being a characteristic of (RO_0000052) only the union of organism (OBI_0100026) and organization (OBI_0000245) to being a characteristic of only material entities (BFO_0000040) is broader and thus shouldn't break any downstream reasoning. So, not being experienced enough in the maintanance of ontology terms, I wonder why you have decided to deprecate the term and not just changed the axioms?

**Comment by dillerm** [comment]
Hi @StroemPhi , we typically deprecate a class if we are making a change to the definition that would change how it is axiomatized. Even though this change was small, we deprecated and replaced 'role in human social processes' (OMRSE:00000024) in keeping with this principle.

**Comment by StroemPhi** [comment]
I see, thank you for the explanation. Unfortunately quite a few of the downstream OBO ontologies didn't notice this change and thus still use the deprecated class.

**Comment by StroemPhi** [comment]
related to: https://github.com/biobanking/biobanking/issues/89

**Comment by StroemPhi** [comment]
As I refreshed my imports I noticed that something went wrong in the current release (v2022-09-06 ) with that class. As can be seen in  
https://github.com/ufbmi/OMRSE/blob/master/src/ontology/omrse-edit.owl#L22 OBIB is imported, which itself imports OMRSE, but not the most current version. This leads to the deprecated "role in human social processes" (OMRSE:00000024) crawling back in, which results in injected axioms (rdfs:subclassOf & rdfs:label):
```
<!-- http://purl.obolibrary.org/obo/OMRSE_00000024 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/OMRSE_00000024">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000023"/>
        <rdfs:subClassOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#ObsoleteClass"/>
        <obo:IAO_0000115 xml:lang="en">A role inhering in an entity realized by social interactions in human society.</obo:IAO_0000115>
        <obo:IAO_0000117 xml:lang="en">Mathias Brochhausen</obo:IAO_0000117>
        <obo:IAO_0000412>http://purl.obolibrary.org/obo/omrse.owl</obo:IAO_0000412>
        <rdfs:comment xml:lang="en">Previous definition: A role played by an entity in human social processes.</rdfs:comment>
        <rdfs:label xml:lang="en">obsolete role in human social processes</rdfs:label>
        <rdfs:label xml:lang="en">role in human social processes</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```
Also, I've noticed that the deprecated class is still used in d-acts causing confusion there -> https://github.com/d-acts/d-acts/issues/35

**Comment by hoganwr** [comment]
This issue appears to be fixed. We will review at next OMRSE meeting (scheduled for Nov 1, 2023) and close if we confirm it.

**Comment by hoganwr** [comment]
Remaining issue: d-acts "owner role" (IAO_0020027) is a subClassOf "obsolete role in human social processes" (OMRSE_00000024)

**Comment by hoganwr** [comment]
Looking more closely, it appears that we do not use "owner role" in OMRSE at the moment.  I therefore propose that we remove "owner role" (IAO_0020027) from the d-acts import.

**Comment by hoganwr** [comment]
Closing because as per above the 2024-01-10 release of OMRSE fixes this issue.
