### ISSUE TITLE
OMRSE relation to CRO

### ISSUE THREAD

**Issue by StroemPhi** [mcwdsi/OMRSE#195]
Looking at the various places in which roles in human social processes are defined in OBO ontologies, I was wondering if it might be possible to bridge or sync with the [Contributor Role Ontology](https://github.com/data2health/contributor-role-ontology)?

**Comment by dillerm** [comment]
Did you have a use case in mind that might motivate this effort? CRO seems to fill a pretty niche domain (research attribution) that I am not sure overlaps with the types of roles and processes that OMRSE represents.

**Comment by hoganwr** [comment]
you are correct that OMRSE is a general home for all kinds of social roles
in OBO.  If there are ways we can help with CRO and align with OMRSE, if
there are higher level classes needed for OMRSE, etc., we'd love to work
iwth you on it.

**Comment by hoganwr** [comment]
For now we are closing this issue.  Feel free to get in touch with future requirements or new term requests for a future alignment of CRO with OMRSE.
