### ISSUE TITLE
Replace 'survey data' (OMIABIS:0000060) with 'survey data' (OBIB:0000667)

### ISSUE THREAD

**Issue by dillerm** [mcwdsi/OMRSE#216]
The OMIABIS class is deprecated.

**Comment by hoganwr** [comment]
That leaves the question as to whether we need to import the OBIB class, or leave "county smoking survey data" as a subclass of "data item" (which in and of itself begs the question of why it's not a subclass of "dataset"). Let's get a resolution at tomorrow's (nov 1, 2023) meeting

**Comment by hoganwr** [comment]
The decision is to leave as is and not import survey data from OBIB.
