### ISSUE TITLE
NTRs: Crime classes

### ISSUE THREAD

**Issue by dillerm** [mcwdsi/OMRSE#221]
For new term requests, please provide the following information:

## Preferred term label

aggravated assault

## Synonyms

none

## Textual definition

Physically abusive behavior in which the aggressor does or attempts to do the following: inflict severe bodily harm on another person with the use of a weapon or by means that are likely to lead to the victim’s death.

## Suggested parent term

physically abusive behavior

## Attribution

Matthew Diller, William R. Hogan

-----------
## Preferred term label

arson

## Synonyms

none

## Textual definition

Abusive behavior in which the aggressor does or attempts to do the following: burn an architectural structure, vehicle, or a material entity owned by another person.

## Suggested parent term

abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

murder

## Synonyms

none

## Textual definition

Physically abusive behavior in which the aggressor does or attempts to do the following: willfully kill another person.

## Suggested parent term

physically abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

simple assault

## Synonyms

minor assault

## Textual definition

Physically abusive behavior in which the aggressor does or attempts to do the following: willfully use physical force against another person without their consent.

## Suggested parent term

physically abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

robbery

## Synonyms

none

## Textual definition

Abusive behavior in which the aggressor does or attempts to do the following: take possession of an entity that belongs to another person by force, threat of force, or violence.

## Suggested parent term

abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

vandalism

## Synonyms

none

## Textual definition

Abusive behavior in which the aggressor does or attempts to do the following: willfully destroy, damage, or deface public or private property without the consent of the owner.

## Suggested parent term

abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

rape

## Synonyms

sexual battery

## Textual definition

Sexually abusive behavior in which the aggressor does or attempts to do the following: penetrate the anus or vagina of another person with any body part without that person’s consent, penetrate the mouth of another person with a sexual organ without that person’s consent, or assault the person in an attempt to do either.

## Suggested parent term

sexually abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

is offense of

## Synonyms

none

## Textual definition

Relation between a behavior and a document that prescribes how people are expected to behave.

## Suggested parent term

topObjectProperty

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

has suspected perpetrator

## Synonyms

none

## Textual definition

Relation between a person and a behavior that is an offense of a legal document, such as a law or ordinance, that prescribes how people are expected to behave.

## Suggested parent term

topObjectProperty

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

curfew ordinance

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that certain people must not leave their home during a given time period.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

breaking curfew

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a local curfew ordinance.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

loitering ordinance

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot idly stand around certain parts of that region without an apparent purpose. 

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

loitering

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a local loitering ordinance.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about disorderly conduct

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot engage in behavior that disturbs the public peace.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

disorderly conduct

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about disorderly conduct.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

illicit drug regulation

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot possess, consume, or sell some drug.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about gambling

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot participate in a process in which bets are made, either as a person making a bet or a person facilitating the betting (e.g., the card dealer); promote betting activities; influence the outcome of a sporting event or contest in an attempt to win a bet; sell, manufacture, purchase, or possess certain gambling equipment; or possess or transmit information about betting.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

illicit drug use

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates an illicit drug regulation by consuming a drug that has been made illegal.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

sale of illicit drugs

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates an illicit drug regulation by selling or seemingly intending to sell a drug that has been made illegal.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about public intoxication

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot drink in public or appear intoxicated while in public.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

public drunkenness

## Synonyms

public intoxication

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about public intoxication.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about driving under the influence

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people at or above a specified blood alcohol content level or who have consumed an illicit drug cannot operate a vehicle.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

driving under the influence

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about driving under the influence.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about embezzlement

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot misappropriate or misapplication of money or property that has been entrusted to their care, custody, or control.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

embezzlement

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about embezzlement.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

neglectfully abusive behavior

## Synonyms

none

## Textual definition

Abusive behavior in which the aggressor does or attempts to do the following: fails to provide for a dependent’s basic needs, such as adequate supervision, food and water, clothing, or housing, through carelessness, indifference, or unwillingness.

## Suggested parent term

abusive behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about neglect of a dependent

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot engage in certain neglectfully abusive behavior.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

lesser offense against the family and children

## Synonyms

criminal neglect

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about neglect of a dependent.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about forgery

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot attempt to alter, copy, or imitate an entity without the consent of the person who owns it with the intention of deceiving or defrauding people.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

forgery

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about forgery.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about fraud

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot attempt to deceive people into giving them something of value or to surrender to them a claimant role they are the bearer of.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

fraud

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about fraud.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

illicit gambling

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about gambling.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

alcohol law

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot manufacture, possess, consume, sell, or transport certain alcoholic beverages, who they are allowed to sell them to, or when they are allowed to sell them.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

violation of alcohol laws

## Synonyms

violation of liquor laws

## Textual definition

Behavior in which the suspected perpetrator violates an alcohol law.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

manslaughter by negligence law

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes what behaviors that result in another person’s death should be considered negligent.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

manslaughter

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a manslaughter by negligence law.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about motor vehicle theft

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot take a motor vehicle from the possession of another person without that person’s consent.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

motor vehicle theft

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about motor vehicle theft.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about misdemeanor sex offenses

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot expose their genitals, breasts, anus, or buttocks in public, such as through public urination, deliberate “flashing,” or public nudity; or touch another person’s genitals, breasts, anus, or buttocks without their consent. 

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

misdemeanor sex offense

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about misdemeanor sex offenses.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

possession of drug

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates an illicit drug regulation by possessing a drug that has been made illegal.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about sex work

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot promote or participate in sexual activities in exchange for some entities of value, including soliciting customers or transporting people for such activities, or owning or operating a facility where such activities occur. 

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

sex work

## Synonyms

none

## Textual definition

Behavior in which the perpetrator violates a regulation about sex work.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about juvenile runaways

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that juveniles who have run away from home can be detained by police if their parents report them missing.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

runaway

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about juvenile runaways.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about stolen property

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot possess, sell, or buy an entity that has been stolen from another person in an act of larceny, motor vehicle theft, robbery, or theft.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

stolen property

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about stolen property.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about larceny

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot take certain entities from the possession of another person without that person’s consent. 

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

larceny

## Synonyms

theft

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about larceny.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about vagrancy

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator or judge, applies to some geographical region, and prescribes that people cannot remain idle in that region or move around in that region without a visible means of support.

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

vagrancy

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about vagrancy.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

regulation about the carrying or possessing of weapons

## Synonyms

none

## Textual definition

A document part for a document that is signed by some legislator, applies to some geographical region, and prescribes that people cannot manufacture, sell, transport, possess, or carry certain material entities that can be used as a weapon. 

## Suggested parent term

document part

## Attribution

Matthew Diller, William R. Hogan
-----------
## Preferred term label

violation of regulation about the carrying or possessing of weapons

## Synonyms

none

## Textual definition

Behavior in which the suspected perpetrator violates a regulation about the carrying or possessing of weapons.

## Suggested parent term

behavior

## Attribution

Matthew Diller, William R. Hogan

**Comment by dexink** [comment]
re. SDOH instruments: "perpetrator" and "victim" ("patient" being somewhat interchangeable with "victim") are used to refer to the persons involved in interpersonal events related to intake and/or patient IPV (intimate partner violence) history

**Comment by dexink** [comment]
Additionally, "prostitution" and related classes should be changed to "sex work" with "prostitution" as an antiquated synonym

**Comment by dillerm** [comment]
Based on @dexink 's recommendations, I changed all uses of 'prostitution' to 'sex work and 'offender' to 'suspected perpetrator'.

**Comment by dexink** [comment]
I am not sure about "suspected perpetrator" as label is highly context specific.
I'm currently looking into overlap of proposed terms with other published ontologies, and will report back.

**Comment by dexink** [comment]
maybe "suspected perpetrator" would be a child of "patient-provided information"? (in the context of the data collection instruments/surveys)

**Comment by dexink** [comment]
also, "sex work" should be changed to "illicit sex work" as some sex work is legal

**Comment by dexink** [comment]
Found a resource on GitHub specifically for legal ontologies, in addition to the terms with overlap in ontologies listed in OntoBee and BioPortal: [https://github.com/Liquid-Legal-Institute/Legal-Ontologies](https://github.com/Liquid-Legal-Institute/Legal-Ontologies)

**Comment by dexink** [comment]
Spoke to Bill about some of this; @dillerm, we are getting dangerously close to "shadow classes" with many of these. We may want to reduce all of this to a limited set of classes, e.g., one "ordinance" or "law" class and one behavior class for violating ordinances/laws.

**Comment by dillerm** [comment]
Ok. In the meantime, I will add these to HERO.

**Comment by dexink** [comment]
A paper I stumbled on that may be helpful (currently or in the future) as it relates to crime classes and medical topics: https://dialnet.unirioja.es/servlet/articulo?codigo=9111486
