### ISSUE TITLE
Replace usages of 'obsolete is owned by' (old OMIABIS OP)

### ISSUE THREAD

**Issue by hoganwr** [mcwdsi/OMRSE#229]
the 'obsolete is owned by' relation is used in axioms on 'health care facility', 'hospital facility', and 'school facility'.

These usages should be replaced by the new relation 'is owned by' in OBIB: http://purl.obolibrary.org/obo/OBIB_0000735

**Comment by dillerm** [comment]
'owns' (OMIABIS:0000008) and 'administrates' (OMIABIS:0000009) should also be replaced by 'owns' (OBIB:0000732) and 'administrates' (OMIABIS:0000733). Neither are used in axioms.
